version: '2.1'
services:

  tele-gpt:
    image: tele-gpt:latest
    restart: always
    container_name: tele-gpt
    network_mode: host
    environment:
      server.port: 8881
      gpt.model: gpt-3.5-turbo

  opentts:
    image: synesthesiam/opentts:all
    restart: always
    container_name: opentts
    restart: always
    ports:
      - 5500:5500


