version: '2.1'
services:

  tele-gpt:
    image: tele-gpt:latest
    restart: always
    depends_on:
      - opentts
    container_name: tele-gpt
    network_mode: host
    environment:
      server.port: 8881
      gpt.model: gpt-3.5-turbo
      tg.api_key: the_key
      gpt.api_key: the_key

  opentts:
    image: synesthesiam/opentts:all
    restart: always
    container_name: opentts
    ports:
      - 5500:5500


